### ISSUE TITLE
Add label with the mount extracted currently

### ISSUE THREAD

**Issue by ferdiaz93** [agusahumada/Homebanking#2]
A label with the extracted money helps the user to know how much money can be extracted

![image](https://user-images.githubusercontent.com/44145617/217447626-f5171a22-a669-4891-872e-85f6c8861dd0.png)

**Comment by agusahumada** [comment]
Label added :)
![imagen](https://user-images.githubusercontent.com/57498057/217458292-4a20a798-e2ad-41be-9444-e7d9cb1b3f49.png)
